### ISSUE TITLE
微信_报警终端用户登陆后功能

### ISSUE THREAD

**Issue by YAYALEECH** [YAYALEECH/HOTHINK_PROJECT#24]
报警终端用户登陆后，显示其手机号已绑定的所有报警终端列表（报警终端id，状态）
点击报警终端后可以查看报警终端详细信息，并且能修改其他手机号，可以增加或者删除、修改，但是当前登陆的手机号不能进行修改删除操作。

**Comment by fangzhouxin** [comment]
已修改
