### ISSUE TITLE
报警拨打电话，手机接听后，还在通话中，还能接到别的报警电话，应该等电话通话结束后才能接到后面的电话。

### ISSUE THREAD

**Issue by YAYALEECH** [YAYALEECH/HOTHINK_PROJECT#3]
测试操作
1、推送it3报警信息
2、手机接到第一个电话后（一直呼叫等待，不要接听），推送it2
3、测试报警界面显示it2火警信息后，按红色键挂断第一个电话，结果：it3报警消息对应的拨打电话记录里第一个电话应该显示“失败”
4、之后手机应该接到第二个电话，接听报警内容应该为it3报警消息。
5、电话还在接听中，又接到第三个电话。
缺陷：第五个操作中，应该等第二个电话接听挂断后才会接到第三个电话

**Comment by fangzhouxin** [comment]
已经修改过程序，请重新测试。
