### ISSUE TITLE
增加群组修改功能

### ISSUE THREAD

**Issue by YAYALEECH** [YAYALEECH/HOTHINK_PROJECT#30]
1、项目工单未提交前，工程经理可以对群组进行修改设置；
2、项目工单提交后，客服跟项目管理员可以对群组进行修改设置。
3、群组号如果不填，则默认为0，判定该设备无群组，群组号不能超过255
4、群组手机号可为空，最多3个。

**Comment by fangzhouxin** [comment]
正在开发。
