### ISSUE TITLE
微信_增加报警终端联系信息修改功能

### ISSUE THREAD

**Issue by YAYALEECH** [YAYALEECH/HOTHINK_PROJECT#31]
如题，报警终端列表里，对每个终端提供【联系信息】按钮，点击后进入火警通知联系信息修改界面：

1、一共可以填6个手机号码，至少有主用户
2、主用户下面增加提示文字：\* 智能卫士上下线时，会短信通知到该用户。
3、在联系信息号码最下面增加提示文字：\* 智能卫士探测到烟雾火警时，会同语音电话同时通知以上全部用户。

**Comment by fangzhouxin** [comment]
已修改
