### ISSUE TITLE
1.3.2测试BUG

### ISSUE THREAD

**Issue by HOTTONY** [YAYALEECH/HOTHINK_PROJECT#4]
目标结果：在接听系统推送的报警语音时，不应该有后续系统推送的报警语音电话。
测试场景:
1.BOSS后台检测到有报警事件：编号：XXXXXXX1 时间：T1
2.就报警事件XXXXXX1第一次向主用户XXX号码推送语音信息，接听中，时间：T1
3.BOSS后台检测到新报警事件：编号：XXXXXX2 时间：T2
4.就报警事件XXXXXX2第一次向主用户XXX号码推送语音信息， 时间：T2
测试结果：
在事件1拨打电话中时，接到了事件2的语音电话
应该的结果为：
事件1拨打电话中，则更新该电话的使用状态，为：拨打中，事件2拨打时，应该先检查该电话的状态，如为拨打中，则转入下一个动作，如未拨打，则进行拨打，并更新该电话的使用状态为拨打中

**Comment by fangzhouxin** [comment]
已经修改过程序，请重新测试。
