### ISSUE TITLE
报警终端失联的报警方式调整需求

### ISSUE THREAD

**Issue by YAYALEECH** [YAYALEECH/HOTHINK_PROJECT#56]
![image](https://cloud.githubusercontent.com/assets/16909615/15562562/dd5f789e-2332-11e6-86ec-fb43129b6e10.png)
 #1、报警终端失联的报警方式增加一个：不通知，即失联报警后只有后台有报警记录，不用通知到用户，调整后为：短信、电话、不通知；默认为不通知
2、可对每个项目设置旗下报警终端失联的报警方式
3、如果报警方式为不通知，报警后自动解除。

**Comment by fangzhouxin** [comment]
已修改
