### ISSUE TITLE
后台增加网关删除功能

### ISSUE THREAD

**Issue by YAYALEECH** [YAYALEECH/HOTHINK_PROJECT#58]
1、需要配置权限
2、已经提交安装的工单不能删除网关，只有正在安装过程中的网关可以删除
3、删除网关时，如网关下有设备，则不允许删除
4、网关如果属于多个项目共有，则只删除当前项目下的网关及设备。

**Comment by fangzhouxin** [comment]
已修改，有设备不能删除。
